[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "package-name"
version = "0.1.0"
description = "..."
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
dependencies = []
